apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: default

  labels:
    app: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-demo
        image: dibyaaaaaaa/devops-demo:v20250727075721
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"